// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Log from "./Log.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Logger$Lbz from "@little-bonsai/rescript-std/src/Logger.mjs";
import * as Option$Lbz from "@little-bonsai/rescript-std/src/Option.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ErrStack$Lbz from "@little-bonsai/rescript-std/src/ErrStack.mjs";

import InkJs from "inkjs"
global.InkJs = InkJs
;

var partial_arg = {
  scope: Log.scope,
  makeDebug: Log.makeDebug,
  makeInfo: Log.makeInfo,
  makeLog: Log.makeLog,
  makeWarn: Log.makeWarn,
  makeError: Log.makeError,
  makeEvent: Log.makeEvent
};

var partial_arg$1 = Logger$Lbz.MakeScope;

var Log$1 = (function (param) {
      return partial_arg$1(partial_arg, param);
    })({
      scope: "Ink"
    });

function tapProm(p, msg) {
  return p.then(function (data) {
              Curry._2(Log$1.log, Caml_option.some(data), msg);
              return data;
            });
}

var List = {};

function get(ink, name) {
  return ink.variablesState[name];
}

function setBool(ink, name, val) {
  Curry._2(Log$1.debug, [
        name,
        val
      ], "setBool");
  ink.variablesState[name] = val;
  
}

function setFloat(ink, name, val) {
  Curry._2(Log$1.debug, [
        name,
        val
      ], "setFloat");
  ink.variablesState[name] = val;
  
}

function setInt(ink, name, val) {
  Curry._2(Log$1.debug, [
        name,
        val
      ], "setInt");
  ink.variablesState[name] = val;
  
}

function setString(ink, name, val) {
  Curry._2(Log$1.debug, [
        name,
        val
      ], "setString");
  ink.variablesState[name] = val;
  
}

function MakeHelpers(Def) {
  var transfer = function (inkEngine) {
    var match = Option$Lbz.map(Option$Lbz.map(inkEngine.variablesState[Def.name + "Config"], (function (prim) {
                return JSON.parse(prim);
              })), Def.t_decode);
    var value;
    if (match !== undefined) {
      if (match.TAG === /* Ok */0) {
        value = match._0;
      } else {
        Curry._2(Log$1.error, [
              Def.name,
              ErrStack$Lbz.fromSpice(match._0)
            ], "Transfer Error");
        value = Def.initialValue;
      }
    } else {
      value = Def.initialValue;
    }
    return function (inkEngine) {
      return setString(inkEngine, Def.name + "Config", JSON.stringify(Curry._1(Def.t_encode, value)));
    };
  };
  var use = function (inkEngine) {
    var match = React.useState(function () {
          return 1;
        });
    var setTick = match[1];
    var value = React.useMemo((function () {
            var match = Option$Lbz.map(Option$Lbz.map(inkEngine.variablesState[Def.name + "Config"], (function (prim) {
                        return JSON.parse(prim);
                      })), Def.t_decode);
            if (match === undefined) {
              return Def.initialValue;
            }
            if (match.TAG === /* Ok */0) {
              return match._0;
            }
            console.log(ErrStack$Lbz.fromSpice(match._0));
            return Def.initialValue;
          }), [inkEngine.variablesState[Def.name + "Config"]]);
    var setState = function (updater) {
      Curry._1(setTick, (function (x) {
              return x + 1 | 0;
            }));
      var newValue = Curry._1(updater, value);
      return setString(inkEngine, Def.name + "Config", JSON.stringify(Curry._1(Def.t_encode, newValue)));
    };
    return [
            value,
            setState
          ];
  };
  return {
          use: use,
          transfer: transfer
        };
}

var Variables = {
  get: get,
  setBool: setBool,
  setFloat: setFloat,
  setInt: setInt,
  setString: setString,
  MakeHelpers: MakeHelpers
};

function debug(inkEngine) {
  console.log([
        "Ink.Debug",
        inkEngine.canContinue,
        inkEngine.state.currentPathString,
        inkEngine.currentChoices,
        inkEngine.currentText,
        inkEngine.currentTags,
        undefined,
        undefined
      ]);
  
}

export {
  Log$1 as Log,
  tapProm ,
  List ,
  Variables ,
  debug ,
  
}
/*  Not a pure module */
