// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Fs$Lbz from "@little-bonsai/rescript-std/src/Fs.mjs";
import * as Logger$Lbz from "@little-bonsai/rescript-std/src/Logger.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

var logLevels_encode = Logger$Lbz.logLevels_encode;

var logLevels_decode = Logger$Lbz.logLevels_decode;

var partial_arg = {
  scope: Logger$Lbz.scope,
  makeDebug: Logger$Lbz.makeDebug,
  makeInfo: Logger$Lbz.makeInfo,
  makeLog: Logger$Lbz.makeLog,
  makeWarn: Logger$Lbz.makeWarn,
  makeError: Logger$Lbz.makeError,
  makeEvent: Logger$Lbz.makeEvent
};

var partial_arg$1 = Logger$Lbz.MakeScope;

var include = (function (param) {
      return partial_arg$1(partial_arg, param);
    })({
      scope: "mercer"
    });

var log = include.log;

var tap = include.tap;

function useWatch(levelOpt, msg, data) {
  var level = levelOpt !== undefined ? levelOpt : "debug";
  React.useEffect((function () {
          Curry._3(tap, level, msg, data);
          
        }), [data]);
  
}

function consoleLogDriver(level, scope, msg, data) {
  var args = [
    scope,
    msg
  ];
  if (data !== undefined) {
    args.push(Caml_option.valFromOption(data));
  }
  if (level === "warn") {
    Caml_splice_call.spliceApply(console.warn, [args]);
  } else if (level === "debug") {
    Caml_splice_call.spliceApply(console.debug, [args]);
  } else if (level === "event" || level === "error") {
    Caml_splice_call.spliceApply(console.error, [args]);
  } else if (level === "log") {
    Caml_splice_call.spliceApply(console.log, [args]);
  } else {
    Caml_splice_call.spliceApply(console.info, [args]);
  }
  
}

function bind(param) {
  return Logger$Lbz.registerDriver(consoleLogDriver);
}

var BuiltInConsole = {
  consoleLogDriver: consoleLogDriver,
  bind: bind
};

function fileLogDriver(path) {
  Curry._2(log, path, "start log file");
  return Fs$Lbz.mkdir(Path.dirname(path)).then(function (param) {
              var writeStream = Fs.createWriteStream(path, {
                    flags: "a"
                  });
              return Promise.resolve(function (level, scope, msg, data) {
                          var lines = [
                            new Date().toISOString(),
                            level,
                            scope,
                            msg
                          ];
                          if (data !== undefined) {
                            var data$1 = JSON.stringify(Caml_option.valFromOption(data));
                            if (data$1 !== undefined) {
                              lines.push(data$1);
                            }
                            
                          }
                          writeStream.write(lines.join("\t") + "\n");
                          
                        });
            });
}

function bind$1(path) {
  return fileLogDriver(path).then(function (driver) {
              Logger$Lbz.registerDriver(driver);
              return Promise.resolve(undefined);
            });
}

var LogFile = {
  fileLogDriver: fileLogDriver,
  bind: bind$1
};

var scope = include.scope;

var makeDebug = include.makeDebug;

var makeInfo = include.makeInfo;

var makeLog = include.makeLog;

var makeWarn = include.makeWarn;

var makeError = include.makeError;

var makeEvent = include.makeEvent;

var debug = include.debug;

var info = include.info;

var warn = include.warn;

var error = include.error;

var $$event = include.$$event;

export {
  logLevels_encode ,
  logLevels_decode ,
  scope ,
  makeDebug ,
  makeInfo ,
  makeLog ,
  makeWarn ,
  makeError ,
  makeEvent ,
  debug ,
  info ,
  log ,
  warn ,
  error ,
  $$event ,
  tap ,
  useWatch ,
  BuiltInConsole ,
  LogFile ,
  
}
/* include Not a pure module */
