// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Option$Lbz from "@little-bonsai/rescript-std/src/Option.mjs";
import * as Random$Lbz from "@little-bonsai/rescript-std/src/Random.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Belt_HashSet from "rescript/lib/es6/belt_HashSet.js";
import ExampleMjs from "../example.mjs";

import InkJs from "inkjs"
global.InkJs = InkJs
;

var storyDef = ExampleMjs;

var coverage = new Set();

function hash(route) {
  return Random$Lbz.hashArr(undefined, route);
}

var eq = Caml_obj.caml_equal;

var RouteHash = Belt_Id.MakeHashable({
      hash: hash,
      eq: eq
    });

var subroutes = Belt_HashSet.make(10, RouteHash);

function runWithWithSubroute(seed, subroute) {
  var story = new InkJs.Story(storyDef);
  var gen = Random$Lbz.gen(seed, undefined);
  var route = [];
  var foundNewNodes = {
    contents: false
  };
  var _i = 0;
  while(true) {
    var i = _i;
    while(story.canContinue) {
      story.ContinueSingleStep();
      var currentPathString = story.state.currentPathString;
      if (!coverage.has(currentPathString)) {
        coverage.add(currentPathString);
        Belt_HashSet.add(subroutes, Array.from(route));
        foundNewNodes.contents = true;
      }
      
    };
    var choices = story.currentChoices;
    var choice = Js_option.firstSome(Option$Lbz.map(Caml_option.nullable_to_opt(subroute[i]), (function (x) {
                return x;
              })), Option$Lbz.map(Random$Lbz.getFromArray(Curry._1(gen, undefined), choices), (function (param) {
                return param.index;
              })));
    if (choice === undefined) {
      return foundNewNodes.contents;
    }
    story.ChooseChoiceIndex(choice);
    route.push(choice);
    _i = i + 1 | 0;
    continue ;
  };
}

var gen = Random$Lbz.gen(undefined, undefined);

function $$do(_param) {
  while(true) {
    console.log([
            "subroutes:",
            Belt_HashSet.size(subroutes).toString(),
            "coverage:",
            coverage.size.toString()
          ].join(" "));
    if (Belt_HashSet.size(subroutes) < 10) {
      runWithWithSubroute(gen(undefined), []);
    }
    var subroute = Random$Lbz.getFromArray(gen(undefined), Belt_HashSet.toArray(subroutes));
    if (subroute !== undefined) {
      var foundNewRoutes = runWithWithSubroute(gen(undefined), subroute);
      if (!foundNewRoutes) {
        Belt_HashSet.remove(subroutes, subroute);
      }
      _param = undefined;
      continue ;
    }
    console.log("stop");
    return ;
  };
}

$$do(undefined);

export {
  storyDef ,
  coverage ,
  RouteHash ,
  subroutes ,
  runWithWithSubroute ,
  gen ,
  $$do ,
  
}
/*  Not a pure module */
